// Local name bank — draws real Western names without asking the model.
//
// Why this exists: the model used to invent every character name. Two failure
// modes came with that. (1) Mode collapse — asked for "a name" it returns the
// same handful of picks, so the same name kept coming back across generations
// however hard the prompt pushed for variety. (2) Invention — asked for a
// tradition it knows thinly it produces a plausible-sounding name that is not a
// real name in that culture. Drawing from a real, frequency-ranked list removes
// both: the randomness is ours (~300k+ combinations per era and gender in the
// English pool alone) and every name is attested.
//
// Data and provenance: src/scripts/name-bank-data.js, generated by
// tools/build-name-bank.py from ONS, US SSA, CSO Ireland and US Census data.
//
// The bank deliberately covers only Western traditions and only the eras its
// sources reach (roughly 1880 to the present). Anything outside that — "Any
// culture" mode, ancient/medieval/far-future eras, non-human name styles — is
// still generated by the model, which is the right tool for those.
const NameBank = (() => {
  const D = typeof NAME_BANK_DATA !== "undefined" ? NAME_BANK_DATA : { given: {}, surnames: {} };

  // Region weights. Anglo-led by design: the app's default is Western
  // characters, and within that the British Isles carry most of the weight.
  const ANGLO_WEIGHTS = { en: 44, us: 16, ie: 15, sc: 14, wa: 11 };
  const CONTINENTAL_WEIGHTS = { fr: 6, de: 6, it: 6, es: 4, nl: 3, nordic: 3 };

  const REGION_LABELS = {
    en: "English", us: "American", ie: "Irish", sc: "Scottish", wa: "Welsh",
    fr: "French", de: "German/Austrian", it: "Italian", es: "Iberian",
    nl: "Dutch/Flemish", nordic: "Scandinavian/Nordic",
  };

  // The picker's time-period values mapped onto the buckets the data supports.
  // Anything absent from this map is outside the bank's range and must go to
  // the model instead — see supportsPeriod().
  const PERIOD_ERAS = {
    any: ["modern", "current", "midcentury"],
    victorian: ["vintage"],
    "early-20th": ["vintage", "midcentury"],
    "mid-20th": ["midcentury"],
    contemporary: ["modern", "current"],
    "near-future": ["current"],
  };

  // Character types whose names are ordinary human names. The rest (demon,
  // alien, elf, fae, angel) need invented phonetics, which the model does well
  // and a bank of real names cannot do at all.
  const HUMAN_TYPES = new Set([
    "any", "vampire", "anthropomorphic", "werewolf", "ghost", "undead", "witch",
  ]);

  // ── names the model overuses ─────────────────────────────────────────────
  // Every LLM reaches for the same small set of "characterful" names. This list
  // is only needed on the paths where the model still invents a name — the bank
  // draws from real data and never needed it — but it lives here so there is
  // one copy, and so draw() can avoid handing out a name the prompts ban.
  //
  // Kept deliberately short. An earlier version also banned ordinary surnames
  // (Stone, Hayes, Cole, Fox, Reid, Price...) and ordinary given names (Clara,
  // Evelyn, Iris, Freya), which backfired: with the normal English namespace
  // ruled out, the model reached for something stranger instead. Only names
  // that are genuinely AI tics, rather than names real people have, belong here.
  const BANNED_SURNAMES = [
    "Voss", "Mercer", "Drake", "Kane", "Vale", "Crane", "Storm", "Dusk", "Mace",
    "Thorne", "Blackwood", "Ravenscroft", "Nightshade", "Ashdown", "Wraith",
  ];
  const BANNED_FEMALE = [
    "Elara", "Seraphine", "Seraphina", "Celeste", "Isolde", "Nyx", "Lilith",
    "Eldra", "Sylvara", "Thalia", "Kaelith", "Vespera",
  ];
  const BANNED_MALE = [
    "Cael", "Rael", "Zael", "Theron", "Oryn", "Kael", "Draven", "Zephyr",
    "Alaric", "Caden", "Brayden", "Aiden",
  ];

  const BANNED_GIVEN_SET = new Set([...BANNED_FEMALE, ...BANNED_MALE].map((n) => n.toLowerCase()));
  const BANNED_SURNAME_SET = new Set(BANNED_SURNAMES.map((n) => n.toLowerCase()));

  // The block injected into prompts where the model picks the name itself.
  const BANNED_NAMES_BLOCK = [
    `- Surnames: ${BANNED_SURNAMES.join(", ")}`,
    `- Female first names: ${BANNED_FEMALE.join(", ")}`,
    `- Male first names: ${BANNED_MALE.join(", ")}`,
    '- Any invented two-syllable name ending in "-ael", "-iel" or "-yn" unless the concept is explicitly high fantasy',
  ].join("\n");

  // ── persistent history ───────────────────────────────────────────────────
  // Shared with the model-driven paths (NameGenShared delegates here) so a name
  // drawn locally is also banned from the prompts, and vice versa.
  const KEYS = { full: "cardgenv2_recent_names", given: "cardgenv2_recent_given", sur: "cardgenv2_recent_surnames" };
  const CAPS = { full: 60, given: 40, sur: 40 };

  function read(key) {
    try {
      const arr = JSON.parse(localStorage.getItem(key) || "[]");
      return Array.isArray(arr) ? arr : [];
    } catch {
      return [];
    }
  }

  function write(key, arr, cap) {
    try {
      localStorage.setItem(key, JSON.stringify(arr.slice(-cap)));
    } catch {
      // localStorage full or unavailable — history just won't persist
    }
  }

  function recentNames() {
    return read(KEYS.full);
  }

  // Records full names and, separately, their parts: banning "Alfie Hodgson"
  // alone would still allow "Alfie Pennington" on the next draw, and repeating
  // a first name is exactly what the user notices.
  function recordNames(names) {
    const list = (Array.isArray(names) ? names : [names]).filter(Boolean).map(String);
    if (!list.length) return;
    write(KEYS.full, [...read(KEYS.full), ...list], CAPS.full);
    const given = [];
    const surnames = [];
    list.forEach((n) => {
      const parts = n.trim().split(/\s+/);
      if (parts[0]) given.push(parts[0]);
      if (parts.length > 1) surnames.push(parts[parts.length - 1]);
    });
    if (given.length) write(KEYS.given, [...read(KEYS.given), ...given], CAPS.given);
    if (surnames.length) write(KEYS.sur, [...read(KEYS.sur), ...surnames], CAPS.sur);
  }

  function clearHistory() {
    Object.values(KEYS).forEach((k) => {
      try { localStorage.removeItem(k); } catch { /* ignore */ }
    });
  }

  // ── pools ────────────────────────────────────────────────────────────────
  function regionWeights(origin) {
    if (origin === "anglo") return { ...ANGLO_WEIGHTS };
    // "western": Anglo-led, with continental Europe as a real but minority
    // presence (~28% of draws).
    return { ...ANGLO_WEIGHTS, ...CONTINENTAL_WEIGHTS };
  }

  function weightedPick(weights) {
    const entries = Object.entries(weights).filter(([r]) => D.given[r] && D.surnames[r]);
    const total = entries.reduce((sum, [, w]) => sum + w, 0);
    if (!total) return null;
    let roll = Math.random() * total;
    for (const [region, weight] of entries) {
      roll -= weight;
      if (roll <= 0) return region;
    }
    return entries[entries.length - 1][0];
  }

  // Which of a region's buckets serve the requested eras. Returns [] when the
  // region's data doesn't reach that era at all, so the draw can skip it rather
  // than substituting something wrong — the curated continental "classic" sets
  // are mid-20th-century, and offering Helga or Jürgen for a Victorian
  // character would be worse than not offering the region at all.
  function eraKeys(byEra, eras) {
    const available = Object.keys(byEra);
    if (!available.length) return [];
    if (available.length === 1 && available[0] === "any") return ["any"];
    const wanted = [];
    eras.forEach((era) => {
      if (byEra[era]) wanted.push(era);
      else if (era === "midcentury" && byEra.classic) wanted.push("classic");
      else if ((era === "modern" || era === "current") && byEra.current) wanted.push("current");
      else if (era === "modern" && byEra.classic) wanted.push("classic");
    });
    return [...new Set(wanted)];
  }

  function givenPool(region, sex, eras) {
    const byEra = (D.given[region] || {})[sex] || {};
    return eraKeys(byEra, eras).flatMap((k) => byEra[k] || []);
  }

  function regionServesEras(region, eras) {
    const sexes = D.given[region] || {};
    return Object.values(sexes).some((byEra) => eraKeys(byEra, eras).length > 0);
  }

  // Names the data shows in genuine use for both sexes — a real androgynous
  // pool rather than a guess at which names read as neutral.
  function neutralPool(region, eras) {
    const female = new Set(givenPool(region, "female", eras));
    return givenPool(region, "male", eras).filter((n) => female.has(n));
  }

  function pick(list) {
    return list.length ? list[Math.floor(Math.random() * list.length)] : null;
  }

  function sexFor(gender) {
    if (gender === "male" || gender === "female") return gender;
    if (gender === "other" || gender === "neutral") return "neutral";
    return Math.random() < 0.5 ? "female" : "male";
  }

  function erasFor(period) {
    return PERIOD_ERAS[period] || PERIOD_ERAS.any;
  }

  // ── drawing ──────────────────────────────────────────────────────────────
  /**
   * Draw `count` distinct full names.
   *
   * @param {object} opts
   * @param {string} opts.gender  female | male | other | any
   * @param {string} opts.period  a picker time-period value (see PERIOD_ERAS)
   * @param {string} opts.origin  anglo | western
   * @param {number} opts.count
   * @param {string[]} opts.exclude  extra names to avoid (e.g. already shown)
   * @param {boolean} opts.record  persist the results to history (default true)
   * @returns {{names: string[], detail: Array<{name, region, sex}>}}
   */
  function draw({ gender = "any", period = "any", origin = "western", count = 1, exclude = [], record = true } = {}) {
    const eras = erasFor(period);
    const weights = {};
    Object.entries(regionWeights(origin)).forEach(([region, weight]) => {
      if (regionServesEras(region, eras)) weights[region] = weight;
    });
    const usedFull = new Set([...recentNames(), ...exclude].map((n) => n.toLowerCase()));
    const usedGiven = new Set(read(KEYS.given).map((n) => n.toLowerCase()));
    const usedSur = new Set(read(KEYS.sur).map((n) => n.toLowerCase()));
    const detail = [];

    for (let i = 0; i < count; i++) {
      let chosen = null;
      // Two passes: the first respects the recent-parts history, the second
      // drops it. A pool can be small (Welsh has 30 given names per sex), so
      // insisting on unused parts forever would eventually find nothing.
      for (let attempt = 0; attempt < 60 && !chosen; attempt++) {
        const strict = attempt < 40;
        const region = weightedPick(weights);
        if (!region) break;
        const sex = sexFor(gender);
        const pool = sex === "neutral" ? neutralPool(region, eras) : givenPool(region, sex, eras);
        const given = pick(pool);
        if (!given) continue;
        // Most people's surname matches their given name's tradition, but not
        // all — an occasional cross-pairing is both realistic and adds variety.
        const surRegion = Math.random() < 0.15 ? weightedPick(weights) || region : region;
        const surname = pick(D.surnames[surRegion] || []);
        if (!surname) continue;
        // A handful of the bank's names are also names the model overuses, and
        // the prompts ban those by name — don't hand out a name the same
        // prompt forbids.
        if (BANNED_GIVEN_SET.has(given.toLowerCase()) || BANNED_SURNAME_SET.has(surname.toLowerCase())) continue;
        const full = `${given} ${surname}`;
        const key = full.toLowerCase();
        if (usedFull.has(key)) continue;
        if (strict && (usedGiven.has(given.toLowerCase()) || usedSur.has(surname.toLowerCase()))) continue;
        chosen = { name: full, region, sex: sex === "neutral" ? "neutral" : sex };
        usedFull.add(key);
        usedGiven.add(given.toLowerCase());
        usedSur.add(surname.toLowerCase());
      }
      if (chosen) detail.push(chosen);
    }

    const names = detail.map((d) => d.name);
    if (record && names.length) recordNames(names);
    return { names, detail };
  }

  /**
   * A shortlist for the full-card prompt: the model still decides the
   * character's gender from the concept, so it needs candidates for each rather
   * than one name imposed up front.
   */
  function shortlist({ period = "any", origin = "western", per = 5 } = {}) {
    // Not recorded here — only the name the model actually picks gets recorded,
    // once the card comes back, so unused candidates stay available.
    const female = draw({ gender: "female", period, origin, count: per, record: false });
    const male = draw({ gender: "male", period, origin, count: per, record: false, exclude: female.names });
    const neutral = draw({
      gender: "other", period, origin, count: 2, record: false,
      exclude: [...female.names, ...male.names],
    });
    return { female: female.names, male: male.names, neutral: neutral.names };
  }

  function supportsPeriod(period) {
    return Object.prototype.hasOwnProperty.call(PERIOD_ERAS, period || "any");
  }

  function supportsType(type) {
    return HUMAN_TYPES.has(type || "any");
  }

  function regionLabel(region) {
    return REGION_LABELS[region] || region;
  }

  function stats() {
    const given = Object.entries(D.given).reduce((acc, [r, sexes]) => {
      acc[r] = Object.values(sexes).reduce(
        (n, byEra) => n + Object.values(byEra).reduce((m, list) => m + list.length, 0), 0);
      return acc;
    }, {});
    const surnames = Object.entries(D.surnames).reduce((acc, [r, list]) => {
      acc[r] = list.length;
      return acc;
    }, {});
    return { given, surnames };
  }

  return {
    draw,
    shortlist,
    recentNames,
    recordNames,
    clearHistory,
    supportsPeriod,
    supportsType,
    regionLabel,
    stats,
    PERIOD_ERAS,
    BANNED_NAMES_BLOCK,
  };
})();
